Feature/421
MetaCell/geppetto-scidash pull request #460
Opened 2020-02-03 17:12 UTC by jrmartin

# %%Card name%%
%%Link to the card%%

## Changes
Short changelog

## Related issues
All issues and cards that are connected with the main card

2020-02-03 17:41 UTC, ddelpiano requested changes

2020-02-03 17:41 UTC, ddelpiano commented on components/model-form/ModelForm.js
> +                        onKeyPress={e =>
we are re-defining the onKeyPress prop, we will lose the first in this case (I think).

2020-02-03 17:41 UTC, ddelpiano commented on components/models/partial.js
> +    if(instance!=undefined){
the linter will bust us here, leave space before and after the !=, also please align the != with !== used below (I always go for the strict check and prefer !== but if there a good explanation for that I am open to debate that). Thx

2020-02-03 17:41 UTC, ddelpiano commented on components/models/partial.js
> +    if(instance!=undefined){
same here

2020-02-03 17:41 UTC, ddelpiano commented on components/models/partial.js
> +      if(instance!=undefined){
and here

2020-02-03 17:41 UTC, ddelpiano commented on components/test-form/ParamsFormset.js
> +        this.updateStateModel(this.props.schema);
this might change, we might need to re-merge if @zsinnema will include the changes suggested. (just a note for us)

2020-02-03 17:41 UTC, ddelpiano commented on shared/adapter/ScoreMatrixGriddleAdapter.js
> +      suiteHashes.add(score.test_instance.test_suites[0].hash);
why only one hash in the Set?

2020-02-03 18:03 UTC, jrmartin commented on components/model-form/ModelForm.js
> +                        onKeyPress={e =>
This is the only onKeyPress for this Chip element, without it is not responding to any key events so there won't be anything to re-define.

2020-02-03 18:05 UTC, jrmartin commented on shared/adapter/ScoreMatrixGriddleAdapter.js
> +      suiteHashes.add(score.test_instance.test_suites[0].hash);
I think this one got mixed in here before the master changes made it to development

2020-02-04 09:48 UTC, ddelpiano commented on components/model-form/ModelForm.js
> +                        onKeyPress={e =>
that was my bad, I mixed this with the one below missing the separator, thx for double checking this.

2020-02-04 09:51 UTC, ddelpiano approved these changes

2020-02-04 11:33 UTC, merged